version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"
    networks:
      - aiq_network
    volumes:
      - ./backend/docs:/app/docs

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - aiq_network

networks:
  aiq_network:
